version: "3"

services:
  api:
    image: apiStudyhelper
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 4000:4000

  website:
    image: websiteStudyhelper
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000